### ISSUE TITLE
panic: runtime error: index out of range [0] with length 0 大佬帮看看咋回事，谢谢

### ISSUE THREAD

**Issue by sdlkhfksl** [pwh-pwh/aiwechat-vercel#50]
panic: runtime error: index out of range [0] with length 0
goroutine 13 [running]:
github.com/pwh-pwh/aiwechat-vercel/chat.(*SimpleGptChat).chat(0xc000152c40, {0xc00013c2c0, 0x1c}, {0xc0001394f0, 0x9})
/vercel/path0/chat/gpt.go:61 +0x6ae
github.com/pwh-pwh/aiwechat-vercel/chat.WithTimeChat.func1()
/vercel/path0/chat/chat.go:177 +0x34
created by github.com/pwh-pwh/aiwechat-vercel/chat.WithTimeChat in goroutine 1
/vercel/path0/chat/chat.go:176 +0x271
Error: Runtime exited with error: exit status 2

**Comment by sdlkhfksl** [comment]
您提供的错误信息是由Go语言的运行时系统打印的，描述了程序执行中发生的一个panic。Panic是Go中的一个术语，指在程序运行时遇到了无法处理的错误条件，通常导致程序崩溃。
出现panic的原因是数组（或切片）索引越界，具体来说是试图访问一个空数组（或切片）的第0个元素，这在Go中是非法的，因为它的长度为0，没有任何元素。
详细来看错误信息:
函数调用栈的顶端是 github.com/pwh-pwh/aiwechat-vercel/chat.(*SimpleGptChat).chat(0xc000152c40, {...}, {...})，意味着问题出现在github.com/pwh-pwh/aiwechat-vercel这个包的chat包中的(*SimpleGptChat).chat方法中。
问题发生在gpt.go的第61行。
后续的两行表示在chat.go的第177行有一个go程被创建并在它的执行过程中遇到了问题，事实上这个问题是在第176行由WithTimeChat函数创建go程时产生的。
Error: Runtime exited with error: exit status 2 表示程序遇到了错误并且以退出状态2结束了运行。
要解决这个问题，您需要查看gpt.go文件的第61行，并找到导致数组越界的原因。可能问题处于代码片段中尝试访问一个空（zero-length）切片或数组的元素。您需要检查在该行之前的代码，以确保对数组或切片的操作是安全的，比如前面是否有检查数组长度的逻辑，或者是索引值是否已经正确设置。

**Comment by pwh-pwh** [comment]
配置redis

**Comment by sdlkhfksl** [comment]
> 配置redis

![屏幕截图 2024-04-01 095113](https://github.com/pwh-pwh/aiwechat-vercel/assets/97817853/43f0b564-f308-41a0-a75d-3c04c318bec7)
配置了，麻烦帮看看啥原因

**Comment by sdlkhfksl** [comment]
Status Code
504
Gateway Timeout 现在变成504 错误了

**Comment by pwh-pwh** [comment]
超时了，问个简单问题，或者换个其他的gpt代理站
